aa = input("Bir şeyler gir1:")
bb = int(input("Bir şeyler gir2:"))
cc = float(input("Bir şeyler gir3:"))
print(type(aa))
print(type(bb))
print(type(cc))
print(aa*2)
print(bb*2)
print(cc*2)
print(str(bb)+aa)