print("╔═════════════════════╗")
print("║     ÇİZİMLER        ║")
print("╠═════════════════════╣")
print("║  1-Kare çiz         ║")
print("║  2-Üçgen çiz        ║")
print("║  3-Daire çiz        ║")
print("║  4-                 ║")
print("║  5-                 ║")
print("║  6-                 ║")
print("║  7-                 ║")
print("║  8-Anamenu          ║")
print("║  9-Çıkış            ║")
print("║                     ║")
print("║    Seçimiz nedir?   ║")
print("╚═════════════════════╝")
secim=input()
if secim=="1": import moduller.cizim_kare
elif secim=="2": import moduller.cizim_ucgen
elif secim=="3": import moduller.cizim_daire
elif secim=="8": print("Anamenüye dönülüyor...")
elif secim=="9": print("Çizimler modülünden çıkış yapılıyor. Hoşça kalın!")
else: print("Geçersiz seçim.")
